### ISSUE TITLE
sharing policy for `Account:Foo` is not overwritten by `Account:Foo:*`

### ISSUE THREAD

**Issue by maxheld83** [SEIAROTg/autobean#14]
Just noticed some unexpected/subtle behavior, though I am not sure whether this is a bug.

If you have these declarations:

```
1990-01-01 custom "autobean.share.policy" "Expenses:Foo"
  share-Alice: 1
  share-Bob: 2

2000-01-01 custom "autobean.share.policy" "Expenses:Foo:*"
  share-Alice: 5
  share-Bob: 1
```

In 2000, for transactions at the *root* of `Expenses:Foo` the 1990 sharing policy is still in place.

Naively, I thought that the wildcard selector means "everything at root and beyond" and that therefore, prior declarations for *only* root would be overwritten.

**Comment by SEIAROTg** [comment]
Yeah this is confusing. What happened is that exact policy and wildcard policy are tracked separately and the exact policy always takes the precedence however old it is, unless replaced by a newer exact policy.

Fixed in 9f7fcc8edb11d086058726124facbf613951a7fa.
